config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :recipe_food, only: [:index, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    get 'publics', on: :collection
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  # get '/user/foods', to: 'users/foods#index', as: :user_foods
  # get 'user/id', to: 'users#show', as: :user
  # post '/user/foods/id', to: 'users/foods#index', as: :user_foods_path


  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "foods#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipeFood
  has_many :ingredients, through: :recipeFood, source: :food

  validates :name, presence: true
  validates :preparation_time_seconds, presence: true, numericality: { greater_than: 0 }
  validates :cooking_time_seconds, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }

  def not_used_ingredients
    user.foods - ingredients
  end

  def need_to_buy_ingredients
    need_to_buy = []

    recipeFood.each do |rf|
      need_to_buy.push(rf) if rf.need_to_buy.positive?
    end

    need_to_buy
  end

  def need_to_buy_ingredients_cost
    cost = 0
    need_to_buy_ingredients.each do |ingredient|
      cost += ingredient.cost_of_need_to_buy
    end
    cost
  end

  def total_recipe_cost
    total_cost = 0
    recipeFood.includes(:food).all.each do |ingredient|
      total_cost += ingredient.total_cost
    end
    total_cost
  end

  def self.publics
    where(public: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @ingredients = @recipe.recipeFood
  end

  # GET /foods/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /public_recipes or /public_recipes.json
  def publics
    @publics = Recipe.publics
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.includes(user: :foods, recipeFood: :food).find params[:id]
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time_seconds, :cooking_time_seconds, :description, :public,
                                   :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label "Preparation Time in Minute", style: "display: block" %>
    <%= form.number_field :preparation_time_seconds, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label "Cooking Time in Minute", style: "display: block" %>
    <%= form.number_field :cooking_time_seconds, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, required: true, size: "50x10" %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit "Create Recipe", class: "btn" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time seconds:</strong>
    <%= recipe.preparation_time_seconds %>
  </p>

  <p>
    <strong>Cooking time seconds:</strong>
    <%= recipe.cooking_time_seconds %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag "user_list"%>

<div class="container ">
  <h1>Recipes</h1>
  <div class= "add-recipe"><%= link_to "New Recipe", new_recipe_path %> </div>
  <% if @recipes.length > 0 %>
    <div class = "recipe-container">
      <% @recipes.each do |recipe|%>
        <div class = "recipe-item">
          <div class = "recipe">
            <div class = "recipe-name">
              <%= recipe.name%>
            </div>
            <div class = "recipe-description">
              <%= recipe.description%>
            </div>
          </div>
          <div class = "wrapped-btns">
            <div class = "recipe-action">
              <%= button_to "Remove", recipe, method: :delete, class: "delete-btn"%>
            </div>

            <div class ="recipe-action">
              <%= link_to "Recipe Details ", recipe_path(recipe)%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class ="empty-msg">
    <h2>There are no Recipes</h2>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class= "form">
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>
</div>

app/views/recipes/publics.html.erb
<%= stylesheet_link_tag "user_list"%>

<div class="container ">
  <h1>Public Recipes</h1>
  
  <% if @publics.length > 0 %>
    <div class = "recipe-container">
      <% @publics.each do |p|%>
        <div class = "recipe-item">
          <div class = "recipe">
            <div class = "recipe-name">
              <%= p.name%>
            </div>
            <div class = "recipe-description">
              <%= p.description%>
            </div>
          </div>
          <div class = "wrapped-btns">
            <div class = "recipe-action first-left">
              <strong class="owner-name">By:  </strong>
              <%= p.user.name%>
            </div>

            <div class ="recipe-action">
              <%= link_to "Details ", recipe_path(p)%>
            </div>

            <div class= "total-items">
              <div class = "recipe-ingredients">
                <strong>Total Food Items: </strong>
                <%= p.ingredients.count %>
                <strong>Total recipe: </strong>
                <%= number_to_currency(p.total_recipe_cost) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class ="empty-msg">
      <h2>There are no Recipes</h2>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<main class="recipe-show" id="<%= dom_id @recipe %>">
  <h1> <%= @recipe.name %> <div class="author"> by: <%= @recipe.user.name %></div> </h1>
  <article class="recipe" >
        <div class=<%= "is-#{@recipe.public ? 'public' : 'private'}"%> >
          <%= @recipe.public ? 'Public' : 'Private' %>
          <label class="switch">
          <input type="checkbox" <%= @recipe.public ? "checked" : "" %> >
          <span class="slider round"></span>
        </label>
        </div>
  <div class="spams">
       
        <div class="preparation_time_seconds">
          <strong>preparation:</strong> <%= @recipe.preparation_time_seconds.seconds.in_minutes %> min
        </div>
        <div class="cooking_time_seconds">
          <strong>cooking: </strong><%= @recipe.cooking_time_seconds.seconds.in_minutes %> min
        </div>
      </div>
      <div class="description">
        <p><%= @recipe.description %></p>
      </div>
    </div>
    <div class="actions">
      <%= link_to "General Shopping List", recipe_food_index_path, class: 'button_to g-s-l' %>
      <%= link_to "Back to recipes", recipes_path, class: 'button_to go-back' %>
      <%= button_to "Destroy this recipe", @recipe, method: :delete, form_class: 'button_to delete' if @recipe.user == current_user %>
    </div>
    <div class="contect">
      <div class="ingredients">
        <%= ( render "recipe_food/add_ingredient", recipe: @recipe ) if @recipe.user == current_user && @recipe.not_used_ingredients.any? %>
        <table>
          <thead>
            <tr>
              <th class="ingredients-head">ingredients</th>
              <th class="amount-head">amount</th>
              <th class="total-cost-head">total cost</th>
              <% if @recipe.user == current_user  %>
                <th class="action-head">actions</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @ingredients.each do |ingredient| %>
              <tr class=<%= ingredient.need_to_buy > 0 ? 'fail' : 'fulfill'  %>>
                <td class="food-name">
                  <%= link_to "#{ingredient.food.name}", ingredient.food %>
                </td>
                <td class="food-amount">
                  <%= "#{ingredient.amount} #{ingredient.food.unit}" %>
                </td>
                <td>
                  <%= "#{ number_to_currency(ingredient.total_cost) }" %>
                </td>
                <td>
                  <%= button_to "Remove", ingredient, method: :delete, class: "delete-btn" if @recipe.user == current_user %>
                </td>
              </tr>

            <% end %>
          </tbody>
        </table>
      </div>
      
  </article>
</main>