config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :recipe_food, only: [:index, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    get 'publics', on: :collection
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  # get '/user/foods', to: 'users/foods#index', as: :user_foods
  # get 'user/id', to: 'users#show', as: :user
  # post '/user/foods/id', to: 'users/foods#index', as: :user_foods_path


  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "foods#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :RecipeFood, dependent: :destroy
  has_many :recipes, through: :RecipeFood

  validates :name, presence: true
  validates :unit, presence: true, inclusion: { in: %w[g gram Kg kilogram L liter ml milliliter piece] }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
    # @foods = Food.find_by_sql("SELECT * FROM foods WHERE user_id = #{current_user.id}")
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= food.unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, required: true, class: "form-input" %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, required: true, class: "form-input" %>
  </div>

  <div class >
    <%= form.submit "Create Food", class: "btn"%>
  </div>
<% end %>

app/views/foods/index.html.erb
<%= stylesheet_link_tag "user_list"%>
<p style="color: green"><%= notice %></p>

<div class="container user-list">
<h1>Foods</h1>

<div class= "add-food"><%= link_to "New food", new_food_path %> </div>
<% if @foods.length > 0 %>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Unit</th>
			<th>Unit Price</th>
			<th>Quantity</th>
			<th>Action</th>
			<th>Details</th>
		</tr>
	</thead>
<tbody>
    <% @foods.each do |food|%>
	<tr>
		<td><%= food.name%></td>
        <td><%= food.unit%></td>
        <td><%= food.price%></td>
        <td><%= food.quantity%></td>
        <td><%= button_to "Delete", food, method: :delete, class: "delete-btn"%></td>
        <td><%= link_to "Detail", food, class: "detail-btn" %></td>
		</tr>
    <% end %>
</tbody>
</table>
<% else %>
  <div class ="empty-msg">
	<h2>There are no foods</h2>
  </div>
<% end %>
</div>

app/views/foods/new.html.erb
<div class = "form">
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<div class = "food-item">
<div class = "owned-by">
  <span>By: </span>
  <%= @food.user.name%>
</div>
<div class = "food-header">
  <strong>Food Name</strong>
  <strong>Unit</strong>
  <strong>Quantity </strong>
  <strong>Unit Price</strong>
</div>
<div class = "food-detail">

  <p><%= @food.name%></p>
  <p><%= @food.unit%></p>
  <p><%= @food.price%></p>
  <p><%= @food.quantity%></p>
</div>

  <div class = "action-wrapper">
  <%= link_to "Back to foods", foods_path, class: "back-btn" %>
  <%= button_to "Delete", @food, method: :delete, class: "destroy-btn" if @food.user == current_user %>
  </div>
</div>
</div>