config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :recipe_food, only: [:index, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    get 'publics', on: :collection
  end

  resources :foods, only: [:index, :show, :new, :create, :destroy]

  # get '/user/foods', to: 'users/foods#index', as: :user_foods
  # get 'user/id', to: 'users#show', as: :user
  # post '/user/foods/id', to: 'users/foods#index', as: :user_foods_path


  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "foods#index"
end

app/views/layouts/_footer.html.erb
<footer></footer>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag "header"%>

<header>
    <div class="logo">
        <%= link_to "Recipe APP" , root_path %>
    </div>
    <nav>
    
    <% if user_signed_in? %>
        <div class="nav-item" >
            <%= link_to "Foods" , foods_path %>
        </div>
        <div class="nav-item" >
            <%= link_to "Recipes" , recipes_path %>
        </div>
        <div class="nav-item" >
            <%= link_to "Public recipes" , publics_recipes_path %>
        </div>
        <div class="nav-item" >
            <%= link_to "shopping list" , recipe_food_index_path %>
        </div>
        <div class="nav-item" >
            <%= link_to "My Profile" , edit_user_registration_path %>
        </div>
        <div class="nav-item">
            <%= button_to "Log out" , destroy_user_session_path, method: :delete, class: "log-out-btn" %>
        </div>
    <% else %>
        <div class="nav-item">
            <%= link_to "Sign up" , new_registration_path(resource_name) %>
        </div>
        <div class="nav-item">
            <%= link_to "Log in" , new_session_path(resource_name) %>
        </div>
    <% end %>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="notification-bar">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
		<%= render 'layouts/header' %>
    <%= yield %>
		<%= render 'layouts/footer' %>
  </body>
</html>